---
- hosts: labservers
  become: yes
  serial:
    - 1
    - 2
    - 50%
  max_fail_percentage: 30
  tasks:
  - name: add host entry
    lineinfile:
      path: /etc/hosts
      line: "aapaeste ansible.aapaeste.com"
